### PR TITLE
Update readme (data-src when using page_scripts)

### PR DESCRIPTION
**Pull request by natxet**
When using page_scripts it is necessary to change from src to data-src on the desired scripts. That was not explained on the readme.

### CODE REVIEW

**Comment by orestbida** [comment]
Hi @natxet,

is this really needed? The plugin should handle both `src` and `data-src` attributes just fine.

**Comment by natxet** [comment]
Sorry, my bad! It did not work for me until I used the data-src and I supposed it was a documentation problem without checking. That was probably a problem with my environment because now it works. But we can change the doc to include that data-src can also work. Maybe better, right?

**Comment by orestbida** [comment]
Yes, I'm fine with that! 

Could you target the `v3.0-beta` branch instead of `master`? Merging master to v3.0-beta is a no go, and any change in master won't be carried over to v3.0-beta (which, will replace everything inside the current master branch).

**Comment by natxet** [comment]
OK! will do!

**Pull request closed without merging**
